# Generated by Django 2.2.6 on 2019-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='screenNo',
            field=models.IntegerField(choices=[(1, 'Screen 1'), (2, 'Screen 2')], default=0),
        ),
    ]
