# Generated by Django 2.2.6 on 2019-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NULL', max_length=20)),
                ('time', models.DateTimeField()),
                ('text', models.CharField(default='NULL', max_length=100)),
            ],
        ),
    ]
