# Generated by Django 2.2.6 on 2019-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenNo', models.IntegerField(choices=[(1, 'Screen 1'), (2, 'Screen 2')], default=0)),
                ('user', models.CharField(default='NULL', max_length=20)),
                ('file', models.FileField(default='NULL', upload_to='video/', verbose_name='')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
