# Generated by Django 2.2.6 on 2019-11-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='durationInSeconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='NULL', upload_to='video/'),
        ),
    ]
